# Generated by Django 5.0.4 on 2024-05-10 07:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='antiqe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/antiqe')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='buety_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/buety_product')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='daily_uses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/daily_uses')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='divices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/divices')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/fashion')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='gerociry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/gerociry')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='kitchen_goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/kitchen_goods')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='leptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/leptop')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='luxury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/luxury')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/mobiles')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='stationary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_brand', models.CharField(default='', max_length=100, null=True)),
                ('product_MRP', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('product_pic', models.FileField(default=' ', null=True, upload_to='product/stationary')),
                ('pro_disc', tinymce.models.HTMLField()),
            ],
        ),
    ]
