# Generated by Django 5.0.4 on 2024-05-10 09:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiqe',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='buety_product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='daily_uses',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='divices',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='fashion',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='gerociry',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='kitchen_goods',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='leptop',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='luxury',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='mobiles',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
        migrations.AddField(
            model_name='stationary',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True),
        ),
    ]
