# Generated by Django 5.0.4 on 2024-05-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emailId', models.EmailField(max_length=254)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
