# Generated by Django 5.0.4 on 2024-05-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_nav',
            name='category',
            field=models.CharField(blank=True, default='not Avelable', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer_nav',
            name='offer_disc',
            field=models.TextField(default='not Avelable', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.FileField(blank=True, default='not Avelable', null=True, upload_to='categaries/'),
        ),
    ]
