# Generated by Django 5.0.4 on 2024-05-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='discription',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='offer_nav',
            name='offer_disc',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
