# Generated by Django 5.0.4 on 2024-05-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_offer_nav_category_offer_nav_offer_disc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_nav',
            name='category',
        ),
    ]
