# Generated by Django 5.0.4 on 2024-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_categories_discription_offer_nav_offer_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='categaries/'),
        ),
    ]
