# Generated by Django 5.0.4 on 2024-05-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_offer_nav_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='disc',
            field=models.TextField(default=' ', max_length=100),
        ),
    ]
