# Generated by Django 5.0.4 on 2024-05-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_categories_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='categaries/'),
        ),
        migrations.AlterField(
            model_name='offer_nav',
            name='offer_disc',
            field=models.TextField(default=' ', max_length=500, null=True),
        ),
    ]
