# Generated by Django 5.0.4 on 2024-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='links',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
