# Generated by Django 5.0.4 on 2024-05-09 11:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_categories_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='links',
            field=autoslug.fields.AutoSlugField(default='', editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
